spring:
  profiles:
    active:
    - default
  application:
    name: decision-tables
  output:
    ansi:
      enabled: always
logging:
  level:
    # Enabling trace for app specific logging.
    com.tvajjala: INFO
    org.springframework: INFO
    org.drools: TRACE
    org.kie: TRACE
